== onecx-parameters

include::./includes/attributes.adoc[]

TIP: This extension currently does not support multi-tenancy.

=== Installation

If you want to use this extension, you need to add the `org.tkit.onecx.quarkus:onecx-parameters` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>org.tkit.onecx.quarkus</groupId>
    <artifactId>onecx-parameters</artifactId>
    <version>{project-version}</version>
</dependency>
----

=== Usage

First you need to add the maven dependency shown at the top

Then you can inject the ParametersService:
[source,java]
----
@Inject ParametersService parametersService;
----
After that you can use the `getValue` Method:
[source,java]
----
String value = parametersService.getValue("key", String.class, "DEFAULT_VALUE");
----

You retrieve either the value from the...

1. Parameter-Service
2. Project application.properties
3. Default Value

in this respective order.

So if you want to retrieve a value from the parameter-service/application.properties and throw an exception if it was not configured there, be sure to set the default-value to null or something else and check if a valid value was returned.

=== Configuration

include::includes/onecx-parameters.adoc[leveloffset=+1, opts=optional]